### PR TITLE
chore: update SideInput UDF example

### PR DESCRIPTION
**Pull request by kohlisid**
Ref: https://numaproj.slack.com/archives/C03GQ3AMHE1/p1729277713165089?thread_ts=1729144626.484519&cid=C03GQ3AMHE1

### CODE REVIEW

**Review by vigith — COMMENTED** [review]
give an example based on the OOP (`class` based) approach?

**Comment by kohlisid** [comment]
@vigith 
Sure! Will update

**Comment by kohlisid** [comment]
@vigith 
Are you good with the functionality aspect though?

**Comment by vigith** [comment]
> @vigith 
> 
> Are you good with the functionality aspect though?

looks good to me. do you have any concerns ?

**Comment by kohlisid** [comment]
@vigith 
Good for me!

**Review by vigith — APPROVED** [review]

**Pull request merged**
