### PR TITLE
chore: refactor example builds so that they no longer rely on tarball

### PR DESCRIPTION
**Pull request by ayildirim21**
Previously to make local references work, we had to run an extra command in order to build a tarball of the SDK. While working on automation for the rust sdk, I found that we can just switch the build context to the root directory, and build our examples from there, thereby no longer requiring the extra step of building the tarball.

### CODE REVIEW

**Comment by kohlisid** [comment]
@ayildirim21 Does this support building directly from examples right now? Or would need to fork the whole repo

**Comment by ayildirim21** [comment]
> @ayildirim21 Does this support building directly from examples right now? Or would need to fork the whole repo

Right now still need to fork the entire repo, this change was just to get rid of the hacky solution of needing to build the tarball first before building the image. We're still tracking the broader issue at [#1658](https://github.com/numaproj/numaflow/issues/1658).

**Comment by KeranYang** [comment]
How was this change tested?

**Comment by ayildirim21** [comment]
> How was this change tested?

ran make image for all the examples to ensure that the image was being built properly.

**Review by vigith — APPROVED** [review]

**Review by KeranYang — APPROVED** [review]

**Pull request merged**
