### PR TITLE
chore: update protobuf version

### PR DESCRIPTION
**Pull request by sandangel**
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>

Kindly explain what this PR does.

### CODE REVIEW

**Comment by sandangel** [comment]
there should be no breaking change https://protobuf.dev/support/migration/

**Review by whynowy — APPROVED** [review]
LGTM

**Review by ab93 — COMMENTED** [review]
This was pinned due to https://github.com/numaproj/numalogic/issues/123

**Comment by sandangel** [comment]
But numaflow-sdk should not depends on numalogic right?

**Review by vigith — APPROVED** [review]

**Pull request merged**
