### PR TITLE
fix: modify Dockerfiles to fix failing image builds

### PR DESCRIPTION
**Pull request by ayildirim21**
Kindly explain what this PR does.

### CODE REVIEW

**Review by vigith — APPROVED** [review]

**Review by ab93 — COMMENTED** [review]
All of these dockerfile examples are non optimized. We should comeback later to fix them

**Review by ab93 — APPROVED** [review]

**Comment by kohlisid** [comment]
@ayildirim21 Tested with images running?

**Comment by ayildirim21** [comment]
> @ayildirim21 Tested with images running?

I ran several of the example pipelines, after pushing their respective images, and did not come across any errors in the container logs

**Comment by kohlisid** [comment]
@ayildirim21 Do verify both approaches once, default and with args in the yaml
Thanks!

**Comment by ayildirim21** [comment]
@kohlisid Ran the `even-odd` example with both
```
      container:
        args:
        - python
        - example.py
```
Present and not, both pipelines ran fine

**Comment by kohlisid** [comment]
Thanks @ayildirim21

**Pull request merged**
