### PR TITLE
feat: Add ID and numDelivered fields to Datum in udf

### PR DESCRIPTION
**Pull request by xdevxy**
As part of https://github.com/numaproj/numaflow/issues/538, this PR adds ID and numDelivered fields to Datum in udf, so that users are exposed with these metadata information about the message.

### CODE REVIEW

**Comment by vigith** [comment]
can you run `make lint`, i feel few changes can be removed if we run the linter.

**Comment by xdevxy** [comment]
> can you run `make lint`, i feel few changes can be removed if we run the linter.
I thought I had, but somehow I missed it.. updated. :)

**Review by vigith — APPROVED** [review]
should we document this in README?

**Comment by xdevxy** [comment]
> should we document this in README?

Sure, will have a follow up PR.

**Pull request merged**
